import React from 'react';
import { useStore } from '../store/useStore.jsx';
import { calculateRatios } from '../utils/financialEngine';
import { detectAnomalies } from '../utils/fraudEngine';
import { Shield, FileText, Download, Printer } from 'lucide-react';
import AnalysisTable from './AnalysisTable';
import RedFlagsPanel from './RedFlagsPanel';
import RiskIndicator from './RiskIndicator';

const ReportPreview = () => {
  const { currentCompany } = useStore();
  
  if (!currentCompany) return null;

  const ratios = calculateRatios(currentCompany.statements);
  const fraud = detectAnomalies(currentCompany.statements);

  return (
    <div className="report-container" style={{ padding: '40px', maxWidth: '1000px', margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px', marginBottom: '24px' }}>
        <button className="glass-card" style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 16px', background: 'transparent', color: 'var(--text-primary)', border: '1px solid var(--border)', cursor: 'pointer' }}>
          <Printer size={16} /> Print
        </button>
        <button className="glass-card" style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 16px', background: 'var(--accent-blue)', color: 'white', border: 'none', cursor: 'pointer' }}>
          <Download size={16} /> Download PDF
        </button>
      </div>

      <div id="pdf-report-content" style={{ 
        background: '#0d1117', border: '1px solid var(--border)', borderRadius: '12px', 
        padding: '60px', color: 'white', position: 'relative', overflow: 'hidden' 
      }}>
        {/* Watermark/Logo */}
        <div style={{ position: 'absolute', top: '-50px', right: '-50px', opacity: 0.05 }}>
          <Shield size={400} />
        </div>

        <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '60px', borderBottom: '2px solid var(--accent-blue)', paddingBottom: '32px' }}>
          <div>
            <h1 style={{ fontSize: '32px', marginBottom: '8px', letterSpacing: '-1px' }}>AlphaVision Forensics</h1>
            <p style={{ color: 'var(--accent-blue)', fontWeight: '700', fontSize: '14px' }}>CONFIDENTIAL AUDIT REPORT</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <p style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>REPORT ID: AV-{Math.random().toString(36).substr(2, 9).toUpperCase()}</p>
            <p style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>DATE: {new Date().toLocaleDateString()}</p>
          </div>
        </header>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ fontSize: '20px', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <FileText size={20} color="var(--accent-blue)" /> Executive Summary
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '32px' }}>
             <p style={{ fontSize: '14px', lineHeight: '1.8', color: 'var(--text-secondary)' }}>
                Detailed forensic examination of <strong>{currentCompany.name}</strong> indicates a {fraud.riskLevel.toLowerCase()} risk profile. 
                The analysis encompasses three fiscal periods with specific focus on revenue recognition integrity, 
                operating cash flow conversion, and balance sheet health relative to industry benchmarks in the <strong>{currentCompany.type}</strong> sector.
             </p>
             <RiskIndicator score={fraud.riskScore} level={fraud.riskLevel} />
          </div>
        </section>

        <section style={{ marginBottom: '60px' }}>
           <h3 style={{ fontSize: '18px', marginBottom: '20px' }}>Foundational Financials</h3>
           <AnalysisTable />
        </section>

        <section style={{ marginBottom: '60px' }}>
           <h3 style={{ fontSize: '18px', marginBottom: '20px' }}>Audit Flag Details</h3>
           <RedFlagsPanel flags={fraud.flags} />
        </section>

        <footer style={{ marginTop: '80px', paddingTop: '20px', borderTop: '1px solid var(--border)', textAlign: 'center' }}>
          <p style={{ fontSize: '11px', color: 'var(--text-secondary)' }}>
            This report is generated by the AlphaVision AI Engine and is intended for professional financial advisory use only.
            Verification against primary source documents is recommended.
          </p>
        </footer>
      </div>
    </div>
  );
};

export default ReportPreview;
